project_type: android
test:
  build:
    ignore: false
    command: gradle :app:assembleDebug
  checkstyle:
    ignore: true
    command: gradle :app:checkstyle
  findbugs:
    ignore: true
    command: gradle :app:findbugs
  pmd:
    ignore: true
    command: gradle :app:pmd
  androidlint:
    ignore: true
    command: gradle :app:lint